### ISSUE TITLE
Limitation in using Long as the type of Id.

### ISSUE THREAD

**Issue by giulio90** [katharsis-project/katharsis-framework#103]
I am using Katharsis-rs to create a rest api which will work upon huge amounts of data. My model consists of resources which are mapped 1:1 with the database tables, most of which have composite primary keys.

My problem is how to assign an id which would guarantee a deterministic uniqueness for each resource. Keeping in mind that I would be dealing with huge amounts of data (exceeding the max value of Long), it would not be possible to generate a long from the primary keys and use this as an id. 

This restricts me in fetching single resources (and their relationships) since I cannot use the 'findOne' method.

Is there some other design which you can suggest in order to tackle this problem? I feel that I am quite restricted by the use of Long as the type for the id.

**Comment by remmeier** [comment]
not an answer, but related to the topic: are you using JDBC or JPA to access the database?

**Comment by giulio90** [comment]
I am using JOOQ : http://www.jooq.org/

**Comment by remmeier** [comment]
there is https://github.com/adnovum/katharsis-framework/tree/master/katharsis-jpa which is still work in progress. It does the same thing you do, but on the JPA layer with either Criteria API or queryDSL. You may want to have a look at it to get some inspiration :-) I guess jooq comes very close to queryDSL. 

It is not 100% ready yet, I currently work on a new query api to replace QueryParams (see https://github.com/katharsis-project/katharsis-framework/tree/query). After that I will polish katharsis-jpa and merge it into the development branch. Hopefully in a weeks time.

Regarding the id stuff. katharsis-jpa has support for JPA embeddable ids, which translates to composite primary keys. For this purpose I use a custom ResourceInformation.parseId(...) to make the composite primary key out of the individual parts encoded as String.

**Comment by chb0github** [comment]
It's impossible for you to exceed the max value of a long. The max value of
a long is 1.8446744e+19.
If you still believe it, then I would love to hear how.

That being said, this forum is not for assisting you with your design. If
you have a specific issue with Katharsis then bring it to our attention.
