### ISSUE TITLE
Type of variable annotated with @JsonApiId ignored in ResourceInformation.idField.type

### ISSUE THREAD

**Issue by barabanger** [katharsis-project/katharsis-framework#106]
I'm not sure if this is an issue or just happened to work before, but considering following code snippet:

```
interface Id {
};

class ScopedId<N,E> implements Id {
    private final N namespaceId;
    private final E entityId; 
};

class ParameterId extends ScopedId<Long,Long> {
};

class Parameter {
    @Nonnull
    @JsonApiId
    private final ParameterId id;

  @Nonnull
   public ScopedId<Long, Long> getId() { return id; }
   ....
};

```

I can see in` ResourceGet::handle`:  
2.4.X: `regsitryEntry.resourceInformation.idField.type = ParameterId`,
2.6.0-SNAPSHOT: `regsitryEntry.resourceInformation.idField.type = ScopedId`,
2.5: `regsitryEntry.resourceInformation.idField.type = Id`.

As I understand, since `id` field marked with `JsonApiId`,  annotation and so type of the variable supposed to be used and not type of the getter.

**Comment by meshuga** [comment]
Yes, it's the best solution. Sorry for the changes.
Related issue: https://github.com/katharsis-project/katharsis-framework/issues/21.

**Comment by meshuga** [comment]
Thanks for the issue!
