### ISSUE TITLE
Spring MVC controller to receive posted JSON returns 400 - Required body missing

### ISSUE THREAD

**Issue by fiftoine** [katharsis-project/katharsis-framework#116]
I've integrated Katharsis (2.5.0) with spring-boot (1.4.0.RELEASE) and I'm realy happy about it.
```
@SpringBootApplication
@Import(KatharsisConfigV2.class)
@Configuration
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```

I began to setup security with an extra spring mvc controller to handle login and logout methods.

But with a RequestBody annotated parameters to convert json (not jsonapi) to java object, I've got a 400 response telling me required body is missing.

```
@RestController
public class AccountController {

    //...

    @RequestMapping(value = "/auth/signup", method = RequestMethod.POST)
    public @ResponseBody AuthenticationResponse signup(
            @RequestBody AuthenticationRequest authenticationRequest) {
        //...
    }

    //...
}
```
When I remove the import for Katharsis configuration, everything goes fine.
```
@SpringBootApplication
//@Import(KatharsisConfigV2.class)
@Configuration
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```
How could I tweak my project configuration to allow basics spring controllers to accept standard JSON?

Thanks in advance

**Comment by Sandmania** [comment]
Try replacing `@Configuration` with `@RestController`

**Comment by fiftoine** [comment]
As I've already annotated `@ResponseBody` on the method `signup` this doesn't change anything...

**Comment by Sandmania** [comment]
Ach, sorry, I thought the `/auth/signup` endpoint was in the `Application` class. What version of katharsis and spring boot are you using? I have a similar setup running with spring boot 1.3.5.RELEASE and katharsis 2.4.0 and it works.

**Comment by fiftoine** [comment]
Spring Boot : v1.4.0.RELEASE
Katharsis : 2.5.0

Thanks for your time

**Comment by fiftoine** [comment]
On the AuthenticationRequest parameter, if I do `@RequestBody(requried=false)` the method is executed but the `authenticationRequest `is empty...

It's as if the body of the request is removed before being read by katharsis.

**Comment by Sandmania** [comment]
Hmm.. upgrading to katharsis 2.5.0 breaks it for me too.

**Comment by fiftoine** [comment]
I just checked the releases and upgrading to 2.6.0 fixed it. Seems 2.5.0 was the problem.
Thanks for your time @Sandmania

**Comment by meshuga** [comment]
Version 2.6.0 has a fix for a bug https://github.com/katharsis-project/katharsis-framework/issues/99 which causes 400.
