### ISSUE TITLE
Unsupported Media Type using katharsis-client

### ISSUE THREAD

**Issue by csetera** [katharsis-project/katharsis-framework#117]
Using 2.6.0 (or 2.7.0-SNAPSHOT), I'm getting an "Unsupported Media Type" exception when trying to call my Katharsis service.  io.katharsis.client.internal.AbstractStub#execute makes the call to the server by setting the Content-Type header:

`Builder complementedBuilder = builder.header("Content-Type", CONTENT_TYPE);`

However, io.katharsis.invoker.KatharsisInvoker#isAcceptableMediaType method checks for an Accept header and when it isn't found, it return false and the request returns with the failure.

I'm not sure if there is a specific reason for the mismatch, but adding an Accept header on the client side seems to fix this issue.

**Comment by remmeier** [comment]
yes, sending an accept header would be correct. PR would be welcomed. In general the client is still very much experimental and requires some more work.

**Comment by chb0github** [comment]
If there is no accept header the I believe it's entirely up to the server
as to what to send. Usually, the request is accepted and a default payload
is returned. That is most handy.

**Comment by csetera** [comment]
Reading the media type section of the JSON:API specification makes this a bit confusing.  In the end, it seems like the client should send a Content-Type and Accept header with the JSON:API content type.

**Comment by remmeier** [comment]
http://jsonapi.org/format/#content-negotiation-clients

have only used JAX-RS so far, there the request gets accepted with the {*/*, q=1000} MediaType. I guess KatharsisInvoker should work in a similar fashion.

**Comment by remmeier** [comment]
seems that there is no need to send the accept header based on the spec.

**Comment by csetera** [comment]
May not be required, but also can't see how it can hurt to send it either.  There is definitely a mismatch with the check in the invoker.  And declaring that the Katharsis client accepts the JSON:API type is certainly not wrong.

**Comment by remmeier** [comment]
PR was merged in a while back
