### ISSUE TITLE
save() doesn't adhere to JSON API PATCH semantics

### ISSUE THREAD

**Issue by weaselmetal** [katharsis-project/katharsis-framework#122]
## Context

In Katharsis `save()` is used for creation and updating.

When used for updating during a PATCH request Katharsis sets **all** the properties on the JsonApiResource POJO in contradiction to the JSON API standard.

> If a request does not include all of the attributes for a resource, the server MUST interpret the missing attributes as if they were included with their current values. The server MUST NOT interpret missing attributes as null values.

## Reproduce

Given a `Person` JsonApiResource with the business rules:
1. Creating a `Person` with no initial attributes is permitted
2. Changing a `Person's attributes to null is **not** permitted.

Creating a person with no initial attributes is also possible because of the default constructor required by frameworks (hibernate, katharsis, etc).

```java
@JsonApiResource(type = "persons")
public class Person()
{
    private Long id;

    private Integer age;

    private String name;

    // default constructor
    public Person() {}

    public Person(String name, Integer age) {
        this.name = name;
        this.age = age;
    }

    @JsonApiId
    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        if (name == null) throw new IllArgEx("...");
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        if (age == null) throw new IllArgEx("...");
        this.age = age;
    }
}
```

Now, I have an instance of Person: `id: 5, name: Jon, age: null`. His age has never been set, so it is null on the server, but I would like to change his name to `John` so I PATCH with:

```json
{
  "data": {
    "type":"persons",
    "id":5
    "attributes": {
      "name":"John"
    }
  }
}
```

**Expected Result**: 

The resource's `setName("John")` method is called, and `setAge()` is never called.

**Actual Result**:
Katharsis calls `setName("John")`  properly, but also calls `setAge(null)` during the PATCH request and triggers the violation of business rule #2.

## Solution?

I'm not sure how to solve this problem but, the reason is that object `DataBody` contains the null field age and `ResourceAttributeBridge.setProperties(...)` will try to set all the attributes it finds in the `DataBody` object.

One could use this nasty workaround:
```java
public void setAge(Integer age) {
    if (this.age != null && age == null) throw new IllArgExc("...");
    this.age = age;
}
```

It's not sensible to overwrite all fields of an object with the values it already holds, because:
* A setter may also do complicated operations like parsing the input, transforming it, etc
* It leads to the type of workarounds above which needlessly pollute the codebsae with noise unrelated to business logic.

**Comment by weaselmetal** [comment]
Since katharsis patches data onto a new vanilla instance of the object first, all kinds of checks inside a setter that are supposed to do different things for new objects, rather than existing objects are bound to break. Patching an existing object will always go through the setter of a newly created object first.

**Comment by Ramblurr** [comment]
@remmeier  This is an old ticket, but I just rewrote the body text (with @weaselmetal 's permission) to be more concise and clear. Any thoughts here? Is this related to #221 ?

**Comment by remmeier** [comment]
In case of a PATCH Katharsis must fetch the current version from the resource repository with findOne and then update only the fields that have been transmitted from the client side. That should work well I guess?

For the jpa repositories I actually already do this to some degree with ResourceUpsert.newResource and the ResourceInstanceBuilder. So it might be a simple thing to do generally.

BTW: with the new V2 versions of the repository interfaces it is also possible to distinguish push/patch within the repositories (save vs create method).

At some point we may also support DTOs having a has<AttrName> methods next to get/set. Or attribute of tye java.util.Optional. If they are not set, they will be ignored. Projectsl ike https://immutables.github.io/ create those has methods out-of-the-box.

**Comment by remmeier** [comment]
(I needed this in the jpa repositories to directly write to the managed entities)

**Comment by Ramblurr** [comment]
> In case of a PATCH Katharsis must fetch the current version from the resource repository with findOne and then update only the fields that have been transmitted from the client side. That should work well I guess?

Yes, this is the expected behavior.

I've attached a PR that modifies the behavior of `ResourcePatch` to match this expectation. All tests pass, but I hope this doesn't break existing usage.

**Comment by giulio90** [comment]
The problem with this however is not only related to updating the setters.  Let's say findOne() performs a call to the database. I do not wish that upon every update, 2 database calls are made ( 1 to get the current value and 1 to update it). Katharsis should be able to provide JUST the elements that were sent inside the patch request. Currently I am translating the request body into a HashMap in order to get just these values such that I perform an update using only the elements provided. Does anyone have other ideas?

**Comment by remmeier** [comment]
you can use POST instead of PATCH (with the new V2 interfaces). 

At some point there should also be support for partial beans, like each property having a "has<propertyName>" method that allows to check whether a given property is set. By default for anything other than this, PATCH should make that read before write.
