### ISSUE TITLE
Can't parse ISO 8601 string into Joda Time DateTime

### ISSUE THREAD

**Issue by jvanantwerp** [katharsis-project/katharsis-framework#128]
I've got a resource with an attribute that is a `joda.time.DateTime` object.  Since `DateTime` doesn't have a `String` constructor, I get the following error message from Katharsis:
 
> "detail": "Exception while reading class com.sf.violet.canonical.type.VioletDate: Can not instantiate value of type [simple type, class org.joda.time.DateTime] from String value ('1997-07-16T19:20:30Z'); no single-String constructor/factory method\n at [Source: N/A; line: -1, column: -1] (through reference chain: com.sf.violet.canonical.type.VioletDate[\"value\"])"

If I create a setter method to accept a string, along with the setter with a `DateTime` argument, Katharsis complains that there are more than one single argument setters.

If I only have the string argument setter Katharsis complains that there is no setter for `joda.time.DateTime`.

What is the correct way in Katharsis for handling this, or is it a bug?

**Comment by remmeier** [comment]
katharsis makes use of Jackson for the json handling, you need to install the corresponding Joda Jackson module in order to get proper serialization/deserialization. That is done with the ObjectMapper that is passed, for example, to the KatharsisFeature (in case of JAX-RS),

**Comment by jvanantwerp** [comment]
Is there an example of how to update the ObjectMapper with Katharsis somewhere that I am missing?

**Comment by mohlek** [comment]
```Java
@Provider
public class KatharsisFeature implements Feature {

	public static final String	APPLICATION_URL	= "";
	public static final String	PREFIX			= "";

	@Override
	public boolean configure(FeatureContext featureContext) {
		final ObjectMapper objMapper = new ObjectMapper();
		objMapper.registerModule(new JavaTimeModule());
		objMapper.setVisibility(objMapper.getSerializationConfig().getDefaultVisibilityChecker().withFieldVisibility(Visibility.ANY).withGetterVisibility(Visibility.NONE));
		final QueryParamsBuilder queryParamsBuilder = new QueryParamsBuilder(new DefaultQueryParamsParser());
		io.katharsis.rs.KatharsisFeature feature = new io.katharsis.rs.KatharsisFeature(objMapper, queryParamsBuilder, new WildflyServiceLocator()) {
			/*
			 * (non-Javadoc)
			 * @see io.katharsis.rs.KatharsisFeature#createKatharsisFilter(io.katharsis.resource.registry.ResourceRegistry, io.katharsis.rs.parameterProvider.RequestContextParameterProviderRegistry, java.lang.String, io.katharsis.dispatcher.RequestDispatcher)
			 */
			@Override
			protected KatharsisFilter createKatharsisFilter(ResourceRegistry resourceRegistry, RequestContextParameterProviderRegistry parameterProviderRegistry, String webPathPrefix, RequestDispatcher requestDispatcher) throws Exception {
				return new AuthenticationFilter(objMapper, queryParamsBuilder, resourceRegistry, requestDispatcher, parameterProviderRegistry, webPathPrefix);
			}
		};
...
}
```
