### ISSUE TITLE
UriInfoServiceUrlProvider not working

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#140]
UriInfoServiceUrlProvider  does not seem to be working, A ConstantServiceUrlProvider is injected when setting up Katharsis within the KatharsFeature.

Likely some kind of request scoping necessary to implement it properly.

**Comment by remmeier** [comment]
implemented a fix, kathars 3.0 should allow a cleaner implementation  where the serialization stack no longer does a lot of processing (computing urls).

**Comment by chb0github** [comment]
This also closes out #42

**Comment by chb0github** [comment]
Thanks Remo :)
