### ISSUE TITLE
Filter does not accept params with period

### ISSUE THREAD

**Issue by narayar** [katharsis-project/katharsis-framework#148]
I cam across this issue if the following request param is passed -- `filter[tasks][first.name]`
the QueryParams object in the repository will have `first.name` as `name`. Its does not populate the param as `first.name`.
I later discovered that this is because of the regex in io.katharsis.queryParams.QueryParams 
String pattern = "[\\w-]+(?<!\\[)(?=\\])";
This regex pattern is chopping the param and eliminating the value before `.`
I just changed the regex to String pattern = "[\\w.-]+(?<!\\[)(?=\\])"; This worked.
Thought would be a good fix since params with period are valid.

**Comment by chb0github** [comment]
Submit a pull request. Happy to have a look and merge.

**Comment by remmeier** [comment]
[first][name] should work, 

unfortunately, the spec is silent what the prefered approach should be.

**Comment by chb0github** [comment]
There was an issue about this the other day. The guy found a problem in the
regex used in Parsing and supplied a better one. No pull request yet

**Comment by narayar** [comment]
I think this fix is not required now. I pulled the latest code from the repo and noticed that the regex has been changed to "[^\\]\\[]+(?<!\\[)(?=\\])". This is accepting all the values.
I was having the older version of katharsis-core. I will sync with the latest code.
