### ISSUE TITLE
Confusing error

### ISSUE THREAD

**Issue by chb0github** [katharsis-project/katharsis-framework#169]
hitting this URL in my test env:

`http://localhost/api/hubs/B1MabhCRA/routes/6e4ba7fd-97ee-40c7-9b6f-926ecac97591?include=driver,vehicle,stops.location,stops.shipments.contact,stops.shipments.location,stops.shipments.tasks`

produces this error

Here is the [code](https://github.com/katharsis-project/katharsis-framework/blob/05274a291c6d06b52edacb60d3eb7cd39465789f/katharsis-core/src/main/java/io/katharsis/request/path/PathBuilder.java#L71)

```
{
  "errors": [
    {
      "status": "500",
      "title": "Resource error",
      "detail": "RelationshipsPath and FieldPath cannot contain ids"
    }
  ]
}
```

I don't understand what it's saying to me and if it's right

**Comment by cjc343** [comment]
It's telling you that you can't filter a to-many relationship URL by id.

While I'm pretty certain it's intended - as the json-api spec doesn't currently specify by-id filtering for to-many relationship URLs - this is a feature I'd love to see personally, either as a revision to the spec, or an optional extension of the spec.

**Comment by chb0github** [comment]
That still doesn't make sense.

Yes, it is a `@JsonAPIToMany` but it's not filtering. It's including.

But, I think what you're saying is "You can't include on id'd resources"? Do you have a link to this in the spec? This is certain to be a hot topic.

And, in looking at this filter: It's including everything that would be in the object anyways. 

At a minimum a clearer error would be good, and this is definitely a 400 error. Katharsis should have a 400 error mapper for this by default. 

If people agree, I will add the mapper to katharsis

**Comment by cjc343** [comment]
This URL without the includes would also fail: `http://localhost/api/hubs/B1MabhCRA/routes/6e4ba7fd-97ee-40c7-9b6f-926ecac97591`

What I'm saying is that you can't filter `routes` by `6e4ba7fd-97ee-40c7-9b6f-926ecac97591
` while accessing that route in relation to the `hub` `B1MabhCRA`. You can only issue a request for all of that hub's routes.

Assuming that the `routes` API exists and answers findOne requests, the following URL would likely work as expected: `http://localhost/api/routes/6e4ba7fd-97ee-40c7-9b6f-926ecac97591?include=driver,vehicle,stops.location,stops.shipments.contact,stops.shipments.location,stops.shipments.tasks`

**Comment by remmeier** [comment]
to fetch relationships you need

GET /articles/1/relationships/comments HTTP/1.1

with /relationships/

And includes needs a type aka include[myType] as long a QuerySpecDeserializer is not setup. I managed to write everything up and do a PR: https://github.com/katharsis-project/katharsis-docs/blob/adnovum_extensions/source/user-docs.rst

**Comment by chb0github** [comment]
On looking at this more I see the reasoning:

`http://host/hub/:id/routes/:id`

is really the same as:

`http://host/routes/:id` 

This is an internal discussion I need to have then. I will close this as "works as designed"

**Comment by chb0github** [comment]
It's still a confusing error. Is there better wording?
