### ISSUE TITLE
Can Error Handling support Checked Exception?

### ISSUE THREAD

**Issue by sothavirak** [katharsis-project/katharsis-framework#173]
Hi,

AnnotatedRepositoryAdapter,

private <TYPE> TYPE invoke(Method method, Object... args) {
        try {
            return (TYPE) method.invoke(implementationObject, args);
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        } catch (InvocationTargetException e) {
            throw (RuntimeException) e.getCause();
        }
    }

Any Checked Exception thrown from Resource will hit ClassCastException due to below line:
throw (RuntimeException) e.getCause();

**Comment by mitch2na** [comment]
I just ran into the same issue! Going to make a fix and PR
