### ISSUE TITLE
Provide access to isUserInRole in katharsis api

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#183]
katharsis is integrated in a variety of environments, but there is currently no way to check security with katharsis api. Instead one has to fallback to the various different apis (jax-rs, servlet, spring, etc.). There should a environment-agnostic isUserInRole(...) method that can be used anywhere.

such an API would facilitate the implementation of filters that perform security checks. For example, before invoking the generic jpa adapters.

**Comment by remmeier** [comment]
implemented for JAX-RS, Servlet to follow

**Comment by Ramblurr** [comment]
This is very interesting! 

Wouldn't it be better if it was one more level abstract?

Ideally there would be basic `canAccess` or `canRead`/ `canWrite` interface that a user could provide to do more comprehensive permission checking?

After all Katharisis doesn't care about users or roles, just if a certain request is allowed. It should be up to the implementation as to how that is decided.

Thoughts?

**Comment by Ramblurr** [comment]
Another idea that would be great is if individual attributes on POJOs could be restricted based on the user role or some mechanism.

**Comment by remmeier** [comment]
isUserInRole is usually what we have more the integration side (Spring, Servlet, JAX-RS).

I actually have a Katharsis SecurityModule in my companies private repositories. That is probably what you are looking for. That one allows you to map roles to GET/POST/PATCH, etc. for some or all resources. It looks like:

´´´
SecurityModule module = SecurityModule.newInstance();
module.addResourcePermission(ManagementRoles.GUEST_ROLE, ResourcePermission.GET);
module.addResourcePermission(ManagementRoles.ADMIN_ROLE, ResourcePermission.ALL);
module.addResourcePermission(Task.class, "taskRole", ResourcePermission.ALL);
´´´

I can contribute that in the near future if you like.

It is still basic, restriction of individual attributes and more would be a great second step.

**Comment by Sandmania** [comment]
I'm interested in the securitymodule that you mentioned. I might also investigate the attribute level security.

**Comment by remmeier** [comment]
ok, i create a pr tomorrow

**Comment by remmeier** [comment]
no longer needed

**Comment by Toilal** [comment]
Docs states this SecurityModule and SecurityConfig, but I can't find those in the classpath. Any help ?
