### ISSUE TITLE
QuerySpec custom fields in filter

### ISSUE THREAD

**Issue by mohlek** [katharsis-project/katharsis-framework#193]
When using QuerySpec it is not possible to filter an entity by fields which are not part of the entity.

I know its an anti-pattern but in some cases I pass fields in my filter so I can react on my API and do certain things. 

> @remmeier 
yes, I assume that does not work so far. The existence of the properly is necessary to obtain the type in order to properly deserialize the filter values. Maybe you could move Class<?> attributeType = PropertyUtils.getPropertyClass(querySpec.getResourceClass(), attributePath); used by DefaultQuerySpecDeserializer into a dedicate method and make it customizable or subclassable (like a ParameterTypeResolver interface or something like that). Maybe another thing comes up as well, but that is what I currently see.

**Comment by Sandmania** [comment]
We are also using this similarly. It would be awesome if this could be supported in the newer versions as well.

**Comment by remmeier** [comment]
introduced flag with setAllowUnknownAttributes to DefaultQuerySpecDeserializer to ignore unknown attributes. 

e.g. 

deserializer = (DefaultQuerySpecDeserializer) katharsisFeature.getQuerySpecDeserializer();
deserializer.setAllowUnknownAttributes(true);
