### ISSUE TITLE
Is there any way to not generate "links" section?

### ISSUE THREAD

**Issue by sloppycoder** [katharsis-project/katharsis-framework#195]
Per json api spec links is not mandatory, is there any configuration to disable generating links in the response?

thanks.

**Comment by remmeier** [comment]
so far only if you provide a custom LinksInformation (which may then be null to provide no links at all)

=>     
ContainerSerializer:

private void writeLinksField(JsonGenerator gen, Object data, RegistryEntry entry) throws IOException {
        gen.writeFieldName(LINKS_FIELD_NAME);
        if (entry.getResourceInformation().getLinksFieldName() != null) {
            gen.writeObject(PropertyUtils.getProperty(data, entry.getResourceInformation().getLinksFieldName()));
        } else {
            gen.writeStartObject();
            writeSelfLink(gen, data);
            gen.writeEndObject();
        }
    }
