### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#212]
- QuerySpec insteadof QueryParams
- Json API compliance
- make use of modules (JPA, Brave, Validation, etc.)

**Comment by Sandmania** [comment]
The current situation is a bit confusing.

- The website points to really old examples. Are those supposed to be maintained at all anymore? http://katharsis.io/examples and https://github.com/katharsis-project/katharsis-examples/
- I think the new and more up-to-date examples are here https://github.com/katharsis-project/katharsis-framework/tree/master/katharsis-examples but...
- ...then there is this branch https://github.com/katharsis-project/katharsis-framework/tree/examples/katharsis-examples and at some point some of the examples referenced in the documentation were available only in this branch. And you kinda just needed to know that.

I understand that there are some major refactoring underway, and this might not be priority one, but for any one new starting to use katharsis, I imagine this is a major PITA.

What I propose should happen under this ticket in the near future:

- Point out the correct location of examples: This way we can update the website.
- Merge the examples branch to master if it contains relevant information and if that has not been done already
- Split the examples update work to smaller tickets: This way others can more easily contribute
- Personally, I'd like to see the examples as more complete showcases of every imaginable feature katharsis can provide for any given module / integration. But this might just be me.

I can contribute to the Jersey examples.

**Comment by remmeier** [comment]
yes katharsis-framework it is for everything. 

I guess the other repositories should either be completed deleted. or if someone cares about the github stars, at least emptied out. there is already a warning that everything has been moved.
