### ISSUE TITLE
Support Nested Inclusions N Levels Deep

### ISSUE THREAD

**Issue by mitch2na** [katharsis-project/katharsis-framework#214]
Right now nested inclusions only work up to the second level. I am in progress of enhancing the serializer to support inclusion values that are N levels down. For example:

localhost/web/project/1?include=tasks.includedProject.tasks

**Comment by chb0github** [comment]
I knew of this limitation too and never got around to filing a ticket. Or did I?

**Comment by mitch2na** [comment]
@chb0github Cool, seems to be working great, but the serialization code is a bit of nightmare. Going to try and clean it up a bit. 

I do have one question, when serializing included data it stops serializing relationship data after the second level. I am guessing it should serialize data as far as it finds it down the chain? Not sure if this might be an issue if some data is self referencing

**Comment by chb0github** [comment]
It should go all the way down. I had to hard code some IncludeByDefault on
fields I knew our UI used. That serialization code is scary which is why I
didn't take it on

**Comment by mitch2na** [comment]
@chb0github Haha i know what you mean! Okay i just finished the last commit for this and i think its good to go. Simplified the inclusion and default / lazy serialization code while adding serialization of all relationship objects down the chain.

**Comment by chb0github** [comment]
Do you have a pr? I can merge it in

**Comment by mitch2na** [comment]
@chb0github Sorry merged it in last night, if you want to review it https://github.com/katharsis-project/katharsis-framework/pull/215
