### ISSUE TITLE
Release notes for 2.8.1 .. (and 2.7)

### ISSUE THREAD

**Issue by Ramblurr** [katharsis-project/katharsis-framework#235]
Over in #171 and #65 I raised the issue that there was no release notes or changelog for 2.7.

Now 2.8.1 is out and there is, yet again, not release notes or changelog.

I'm sorry to be a nag about this, but release notes and changelog is crucial for those in the community to understand what is happening in Katharsis.

- Are there breaking changes?
- What are the major new features?
- What major bugs were fixed?
- Why should we update (or hold off)?

The meeting notes are great and we read them, I wish the same care was taken to documenting releases. 

Release notes are easy to add on github, just click the "add release notes" link under the releases -> tags section.
![tags_ _katharsis-project_katharsis-framework](https://cloud.githubusercontent.com/assets/14830/20621051/0a928c34-b2fd-11e6-8329-a126b1c2395d.png)

#### Obviously this is an ongoing problem. Let's work together to put some policies in place. **How can we lower the friction and make this easier?**

**Comment by chb0github** [comment]
This is my fault. I didn't know how to do it. Next release I will consult
with you and do this. Better?

**Comment by Ramblurr** [comment]
Definitely!

**Comment by Ramblurr** [comment]
Definitely! Ping me here or send me an email directly!

**Comment by chb0github** [comment]
Consider yourself pinged. I am going to do a release here shortly

**Comment by chb0github** [comment]
I am looking at what you pointed out, and that is free form. Previous release note releases seem to be nothing more than a culling of the commits from github. Hope to here from you soon

**Comment by chb0github** [comment]
Release notes added for 3 last versions. 2.8.2 is released.

**Comment by Ramblurr** [comment]
Sorry for not responding in time @chb0github  but this is super :D thanks for this. A list of commits and issues is better than nothing. 

Hopefully in the future the community can come together to summarize the changelog into a simple

**Major New Things**

**Minor Changes**

**Bug Fixes**

list for easy comprehension.
