### ISSUE TITLE
Documentation for using katharsis with Spring MVC

### ISSUE THREAD

**Issue by hvgotcodes** [katharsis-project/katharsis-framework#239]
New user here, sorry for the basic question.  I am having trouble integrating Katharsis with SpringMVC.  Is it possible to use Katharsis in Spring for only JSON-Api serialization/de-serialization?  

If so how would I tell Spring that when a @JsonApiResource is returned from a controller to serialize to JSON-API?

I am asking in the context of SpringMVC, not SpringBoot.  It seems like a lot of the Spring integration provided is in the context of SpringBoot.

**Comment by adhamhf** [comment]
I'd like to be able to use a standard Spring controller with Katharsis so that I can write tests with the mock mvc builders.   I think I could do that using this same information...

**Comment by Ramblurr** [comment]
This is an interesting question, and I'm not sure it is possible. Maybe @remmeier or @chb0github could comment on that.

**Comment by remmeier** [comment]
I guess a JAX-RS setup with SpringServiceDiscovery in the classpath would be very easy to setup in a plain Spring app.

not sure about how deeply it integrates with spring boot. Three is no connection to spring data as far as I know. And the spring boot-specific stuff looked fairly simple. Potentially we could just provide a spring xml or application config without any spring boot. But I'm not using spring, so no guarantees...

**Comment by hvgotcodes** [comment]
@remmeir would it be possible to use just the json-api serialization/deserialization functionality with Spring?  Perhaps by extending `GenericHttpMessageConverter` and registering that?  What part of Katharsis is actually doing the reading/writing of json?

**Comment by remmeier** [comment]
currently it is integrated as AbstractKatharsisServlet and KatharsisInvoker does the reading/writting.

**Comment by Ramblurr** [comment]
> Potentially we could just provide a spring xml or application config without any spring boot.

@remmeier Yes that's what we're doing actually. We used most of the Java configuration from katharsis spring, but then used the KatharsisInvokerBuilder filter from the jersey example. We couldn't use the spring filter as it uses `SpringParameterProvider` which seems [heavily](https://github.com/katharsis-project/katharsis-framework/blob/05274a291c6d06b52edacb60d3eb7cd39465789f/katharsis-spring/src/main/java/io/katharsis/spring/SpringParameterProvider.java#L55) integrated with some spring mvc or boot stuff we don't use.

At some point I'd like to refactor  the spring library to support the more generic xml / app config, but this still has nothing to do with spring MVC.

**Comment by chb0github** [comment]
Closing this unless someone else has something more to add
