### ISSUE TITLE
Unmarshalling Relationship Sets in order requested

### ISSUE THREAD

**Issue by mitch2na** [katharsis-project/katharsis-framework#241]
When unmarshalling relationship resources with Set type, katharsis will create a HashSet that changes the order of the data. It should represent the order the set was requested with.

PR made

**Comment by chb0github** [comment]
As I said in the PR - if we are being picky like this (and, that isn't such a bad idea anyways) then we should not marshal out sets - They should always be List so they are indexable. After all: JSON has nothing but array
