### ISSUE TITLE
Spring Boot, katharsis.domainName value is being ignored in application.properties

### ISSUE THREAD

**Issue by dujmo** [katharsis-project/katharsis-framework#246]
As the title says, the katharsis.domainName value set in the application.properties file is being ignored.
This issue is present since version 2.6.0. Version 2.5.0. uses katharsis.domainName correctly.
Debugging has brought me to the KatharsisRegistryConfiguration class which no longer uses the katharsis.domainName value when creating the URI.

**Comment by chb0github** [comment]
That is correct. That property should have been removed from wherever you
found it. By design, Katharsis will use the host header to generate links.
That property was to achieve the same effect but is there no longer in use

**Comment by dujmo** [comment]
Okay. If that is the case could you please tell me what I should do in this case without the domainName?

Example:
server.contextPath=/application-root

katharsis.resourcePackage=com.my.domain
katharsis.pathPrefix=/api


Katharsis generates this:
http://localhost:8080/api/versions/1/report"

My application expects an URI like this:
http://localhost:8080/application-root/api/versions/1/report"

**Comment by chb0github** [comment]
Mmm,

How about `katharsis.pathPrefix=application-root/api`

Path prefix is a concatenation and nothing more

**Comment by dujmo** [comment]
That exposes the REST endpoint on this route:
http://localhost:8080/application-root/application-root/api/versions/1

Katharsis generates links like this:
http://localhost:8080/application-root/api/versions/1/report

I think the problem would be solved if Katharsis somehow used server.contextPath when creating URI-s.
I don't think it's possible to use server.contextPath in Spring Boot with Katharsis the way it works now.

**Comment by chb0github** [comment]
That's a bug then, because it should concatenate the prefix with the host
header. Can create a branch and reproduce the problem from our examples?

**Comment by dujmo** [comment]
Here you are:
https://github.com/dujmo/katharsis-examples

I've reproduced the problem in the spring-boot-simple-example project.

**Comment by dujmo** [comment]
I tried to deploy an application that uses Katharsis on my server and noticed another problem with the URI generation in links.
In this example I didn't use server.contextPath at all.

I set the pathPrefix like this:
katharsis.pathPrefix=/application-root/api

e.g.
My domain, expected endpoint:
http://app.company.com:8888/application-root/api/groups

Katharsis generated link:
http://localhost:9080/application-root/groups

So Katharsis messed up the URI generation, with the host part and even with the pathPrefix part of the URI.
I'm reverting to version 2.5.0. while the issue is present.
Please tell me if you need anymore information to help fix this.

**Comment by chb0github** [comment]
I will try to have a look. I can't imagine why this is happening. It's
pretty simple

**Comment by chb0github** [comment]
Ok, I checked out your code and ran it. Produced what you were seeing easy enough. Then it occurred to me: This `server.contextPath=/application-root` is nothing I have ever seen before. I checked our whole code base -- It's not there.

Interestingly enough it **does** effect this. In any event, I don't know why you have it in your config. 

Here is the new config file, in it's entirety:

```
katharsis.resourcePackage=io.katharsis.example.springboot.simple.domain
katharsis.pathPrefix=/application-root/api

```
reponds to:
`http://localhost:9999/application-root/api/projects/`

produces:

```
{
  "data": [
    {
      "type": "projects",
      "id": "123",
      "attributes": {
        "name": "Great Project"
      },
      "relationships": {
        "tasks": {
          "links": {
            "self": "http://localhost:9999/application-root/api/projects/123/relationships/tasks",
            "related": "http://localhost:9999/application-root/api/projects/123/tasks"
          }
        }
      },
      "links": {
        "self": "http://localhost:9999/application-root/api/projects/123"
      }
    }
  ],
  "included": []
}
```

which is exactly what you were after.

**Comment by chb0github** [comment]
Ok, I thought about this a bit and re read your comments. This is obviously a magic property that spring uses. The solution is to work with their property. In addition, this would not be a backward compatible change. But an easy fix.  So, throwing a bit of code in there to check for the old property and throw an error if set is in order

**Comment by dujmo** [comment]
server.contextPath is a Spring Boot property for setting the application
root.

Here is a short explanation on how it works:
http://stackoverflow.com/questions/20405474/spring-boot-context-root

The bigger problem is the behaviour when deployed on a real server when
server.contextPath isn't used and this:
http://app.company.com:8888/application-root/api/groups

Becomes this:
http://localhost:9080/application-root/groups

**Comment by chb0github** [comment]
Yeah, I got it. I understand. I get what the fix is. I will get to it when I can

**Comment by chb0github** [comment]
This is easy enough to support; the elder involved in this was occupied saving the free world. 

To implement this, basically Katharsis would stop using (directly) it's own property and just key off of the spring property. And support some backward compatibility.
