### ISSUE TITLE
Snapshots in Maven Central?

### ISSUE THREAD

**Issue by corrspt** [katharsis-project/katharsis-framework#251]
Hi guys,

I was wondering if this was (or is) possible: Katharsis latest release is 2.8.1, but there have been lot's of merged PR's recently with changed we can't try because of them not being available in maven central. Would it be possible to publish the latest master everytime to maven central (a snapshot?).

If there's another way to test using the master branch, I'm open to suggestions. I do however use Heroku for deploying, as such if the solution involves some sort of "local maven repository" it would work for local testing, but not for testing that in staging/production.

Thanks for the project and all the work that's been put into Katharsis lately, very glad to see it :)

**Comment by mohlek** [comment]
I really like the snapshot idea and the master branch

/cc @masterspambot @chb0github @remmeier

**Comment by chb0github** [comment]
We can talk about this today in Hangouts. It's definitely the way to go. I
need to take the time to set it up

**Comment by chb0github** [comment]
Oh, wait. I reread this. I want to setup a pipeline of one commit, one release. Then you can try right away.

**Comment by mohlek** [comment]
are we talking about a full release or a snaphot release?

**Comment by corrspt** [comment]
Well, when I opened the issue I was essentially thinking of being able to test out some feature/bug fix that get's merged in a pull request without having to wait for a full release.

**Comment by chb0github** [comment]
I am talking about full release. Why not? Why do you need a MEGA release? Whenever you're using a snapshot release you never quite know what you're getting because it can be overwritten or out-of-date.
