### ISSUE TITLE
katharsis-jpa should respect getters not just fields

### ISSUE THREAD

**Issue by Ramblurr** [katharsis-project/katharsis-framework#260]
Another hiccup when trying to katharsis-jpaify my project.

Unfortunately the projects I want to use katharsis with don't always have the cleanest POJOs, legacy code, etc etc.

So there can exist getters such as:

```java
public Long getSpecialInterfaceMethod() {
 return getId();
}
```

The reflection that katharsis-jpa uses in [`io/katharsis/jpa/internal/meta/impl/MetaDataObjectImpl.java#initAttributes`](https://github.com/katharsis-project/katharsis-framework/blob/51d1f70c501ee093d99c51ff3c6e193861e122a2/katharsis-jpa/src/main/java/io/katharsis/jpa/internal/meta/impl/MetaDataObjectImpl.java#L77) isn't respecting getters.

```java
	Class<?> implClass = this.getImplementationClass();
		PropertyUtilsBean utils = BeanUtilsBean.getInstance().getPropertyUtils();
		PropertyDescriptor[] descriptors = utils.getPropertyDescriptors(implClass);
		for (PropertyDescriptor desc : descriptors) {
...
```
`PropertyUtilsBean` will return not just plain fields but also "fields" with no backing class level field. In the example above the "field" name is `specialInterfaceMethod` later in [`io.katharsis.jpa.internal.JpaResourceInformationBuilder#toField`](https://github.com/katharsis-project/katharsis-framework/blob/51d1f70c501ee093d99c51ff3c6e193861e122a2/katharsis-jpa/src/main/java/io/katharsis/jpa/internal/JpaResourceInformationBuilder.java#L263) when `beanClass.getDeclaredField` is called, katharsis errors out as the "field" `specialInterfaceMethod` is not a declared field, but instead a getter method on the bean.

The reflection katharsis-jpa uses should gracefully handle declared fields and getters.

[`ClassUtils`](https://github.com/katharsis-project/katharsis-framework/blob/51d1f70c501ee093d99c51ff3c6e193861e122a2/katharsis-core/src/main/java/io/katharsis/utils/ClassUtils.java) in katharsis-core already has a lot of boilerplate reflection for this. 

For example:

* [List<Method> getClassGetters](https://github.com/katharsis-project/katharsis-framework/blob/51d1f70c501ee093d99c51ff3c6e193861e122a2/katharsis-core/src/main/java/io/katharsis/utils/ClassUtils.java#L109)

Couldn't this be used in katharsis-jpa as well?

**Comment by chb0github** [comment]
What you're saying is that the code base sucks :) -- I can get on board. I
frankly think it's ripe for a total rewrite, honestly.There is a whole lot
of intanceof type checking that breaks polymorphism too.

**Comment by remmeier** [comment]
yes, I already work in this area. It resembles some things from my past and I gradually move away from it. One of the next steps is to setup builders and move all logic out of the meta classes so they become plain pojos. That would make fixing this bug here as well. 

getSpecialInterfaceMethod returns "id", did not consider something like that...

**Comment by remmeier** [comment]
at some point ResourceInformation might get beefed up a bit and they meta classes are not necessary at all.

**Comment by remmeier** [comment]
MethodAnnotatedEntityTest added
