### ISSUE TITLE
Respond with 404 status for single resources that do not exist

### ISSUE THREAD

**Issue by buschtoens** [katharsis-project/katharsis-framework#272]
In accordance with the JSONAPI spec ([Fetching Resources > 404 Not Found](http://jsonapi.org/format/#fetching-resources-responses-404)) Katharsis must respond with a `404 Not Found` status for requests to single resources that do not exist. It currently responds with `200 Ok`.

The response body is also incorrect: 

```json
{
  "data": null,
  "included": []
}
```

Although the empty `included` array is unnecessary, it is not illegal per se, as `data` is provided. However, `"data": null` is illegal in this context and so `included` is also.

Instead Katharsis should either respond with an empty response body (discouraged) or a proper `errors` field. There's an issue over at https://github.com/json-api/json-api/issues/1122#issuecomment-265552691 elaborating on that.

The perfect response would look similar to this:

```json
HTTP/1.1 404 Not Found
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "http://example.com/authors/unknown-author"
  },
  "errors": [
    {
      "status": "404",
      "title": "Not Found",
      "detail": "Could not find a resource of type 'author' with id 'unknown-author'."
    }
  ]
}
```

The only exception to this rule is when requesting a single resource via a relationship link that is not yet set:

```json
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "http://example.com/articles/1/author"
  },
  "data": null
}
```

**Comment by chb0github** [comment]
Definitely a bug. Pr is welcome
