### ISSUE TITLE
Cleanup use of KatharsisMatchingException

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#274]
Katharsis should play nice with other non-JSONAPI repositories like JAX-RS and Spring MVC. So everything that does not match a JSON API request should be handled. In this case the KatharsisMatchingException is appropriate (or maybe rather not throw an exception at all).

All the other exceptions should be of time KatharsisMappableException, should not be ignored and return with a proper HTTP error code.

This includes:
- RepositoryAnnotationNotFoundException
- ResourceNotFoundException
- ParserException
- RepositoryInstanceNotFoundException

It should be up the the PathBuilder to decide whether it is a JSON API request or not. Everything after that assumes it is one and returns a response (normal or otherwise).

**Comment by chb0github** [comment]
Yeah, I am on board with this. Katharsis doesn't play nice when you have other non jsonapi resources involved

**Comment by k-sever** [comment]
👍 for this one.

I have one comment. 
Can we also add support for "/" endpoint call? Currently there is a [check](https://github.com/katharsis-project/katharsis-framework/blob/master/katharsis-core/src/main/java/io/katharsis/request/path/PathBuilder.java#L57) that verifies the passed endpoint is non-empty (considering "/" as an empty endpoint):
```
if (strings.length == 0 || (strings.length == 1 && "".equals(strings[0]))) {
        throw new ResourceException("Path is empty");
}
``` 
What's the reason to restrict calling "/"?

I'm not sure whether it deserves a separate ticket or it's fine to attach it to this one.

**Comment by remmeier** [comment]
no longer needed
