### ISSUE TITLE
Add -Xdoclint:none additionalparam to maven-javadoc-plugin when using jdk1.8

### ISSUE THREAD

**Issue by Sandmania** [katharsis-project/katharsis-framework#283]
Java 8 introduced DocLint, which is a quite strict linter for javadoc. By default, the linter will fail the build if there are errors. I feel that failing the whole build is a bit too much, so I'd suggest that the behaviour of maven-javadoc-plugin should be changed so, that only warnings are issued on linter findings, rather than errors.

**Comment by chb0github** [comment]
Love this!

**Comment by chb0github** [comment]
Update the pr so we can merge

**Comment by Sandmania** [comment]
In master.
