### ISSUE TITLE
Creating a Resource while supplying relationships doesn't work

### ISSUE THREAD

**Issue by yuvalbo** [katharsis-project/katharsis-framework#292]
The following example of the spec doesn't work http://jsonapi.org/format/#crud-creating
I am `POST`ing the following data

```
{
	"data": {
		"type": "videos",
		"attributes": {
			"posterUrl": "http://test.mp4",
			"name": "video9",
			"format": "MP4",
			"videoSources": [{
				"type": "LIVE",
				"format": "MP4",
				"publicUrl": "http://videosource.mp4",
				"filePath": "/var/lib/"
			}]
		}
	},
    "relationships": {
      "createdBy": {
        "data": { "type": "users", "id": "4" }
      }
    }
}
```

The createdBy relationship is ignored, and is not supplied during 
```java
@JsonApiSave
  public <S extends Video> Video save(@Valid S video)
```

nor does any method on the RelationshipRepository is being called to make the link.

**Comment by chb0github** [comment]
Definite feature missing. Surprised it wasn't spotted earlier. What happens
when you do this? You say "Doesn't work". Do you get an error? Which error?
Does it partially work?

**Comment by yuvalbo** [comment]
@chb0github There isn't any error - I get a call to save the resource while the property `createdBy` which holds a `User` Resource is received `null`
I would expect the FW to use the RelationshipRepository to assign the provided relationship.
I agree with your saying:
> Surprised it wasn't spotted earlier.  

I still hope I am doing something wrong ;)

**Comment by yuvalbo** [comment]
Bad placement of the relationships property...

**Comment by chb0github** [comment]
Thanks for the update
