### ISSUE TITLE
Support untyped, fully dynamic repositories

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#302]
It should be possible to build up repositories at runtime. Such repositories would lack any compile-time data structures like resource classes. Instead, a ResourceRepositoryV2<Resource, String> could be implemented. 

With the new serialization infrastructure and the resource/repository information builds, support is already mostly in place. Some further minor modifications are necessary, like:

- make sure to identity resources by resourceType instead of its java class (multiple repositories will share "Resource" as class)
- allow to pass resourceType insteadof Resource class to QuerySpec constructor
- bypassing object (de)serialization on client and server side for such repositories

**Comment by chb0github** [comment]
Can you prototype this before doing any serious work?

**Comment by remmeier** [comment]
yes, I work on it. Some more thing need to come. But basically it is already possible.

**Comment by remmeier** [comment]
almost at least...

**Comment by remmeier** [comment]
no longer needed
