### ISSUE TITLE
Move documentation to AsciiDoc and include in katharsis-framework

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#305]
- AsciiDoc integrates well with Maven and Gradle
- having it in the same repo allows the inclusion of code snippets (instead of cop/pasting them)
- actual conversion should be quite easy as it just needs to be translated from a very similar markup langage.

**Comment by chb0github** [comment]
Why would we not just stick with basic markdown? We already have a plugin that generates markdown on build

**Comment by remmeier** [comment]
build setup could make use of https://github.com/asciidoctor/jekyll-asciidoc-quickstart to integrate everything into github

**Comment by Ramblurr** [comment]
I also thing keeping the documentation in the same repo as the source is a good idea. AsciiDoc is a good choice, but I would also suggest [AsciiDoctor](http://asciidoctor.org/) as the parser/toolchain for building the docs. It has great Java + Maven support.

Spring uses it for it's guides and reference manuals with great success.

Examples of asciidoc + AsciiDoctor docs:
* http://docs.spring.io/spring-data/data-commons/docs/current/reference/html
* https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/

Examples of Usage:

* https://github.com/spring-guides/getting-started-guides/wiki/Working-with-AsciiDoctor
* https://spring.io/blog/2013/12/13/spring-s-getting-started-guides-migrated-to-asciidoctor

**Comment by remmeier** [comment]
no longer needed
