### ISSUE TITLE
Implementing `JsonApiExceptionMapper` and `ExceptionMapper` indirectly doesn't work

### ISSUE THREAD

**Issue by k-sever** [katharsis-project/katharsis-framework#310]
Exception mapper that does not implement `JsonApiExceptionMapper`/`ExceptionMapper` directly (does not have `implements JsonApiExceptionMapper` statement right after class definition) is not getting resolved correctly by `ExceptionMapperRegistry`.

This means that I can't move common logic to some abstract mapper (which looks like a common case):

```
@ExceptionMapperProvider
public class MyExceptionMapper extends AbstractExceptionMapper<SomeException>
...
abstract class AbstractExceptionMapper<T extends Throwable> implements JsonApiExceptionMapper<T>
```

Currently to workaround this issue I have to add `implements JsonApiExceptionMapper` to the class definition even though it already implements it indirectly:
```
@ExceptionMapperProvider
public class MyExceptionMapper extends AbstractExceptionMapper<SomeException> implements JsonApiExceptionMapper<SomeException>
```

**Comment by remmeier** [comment]
you may need to have a look at ReflectionsServiceDiscovery. maybe filter.includePackage needs to be called for the exception mapper packages to make sure the scanner can properly resolve the type hierarchy. 

the problem should not happen if one of the CDI or Spring service discoveries is used.

**Comment by k-sever** [comment]
I believe I could clearly spot the issue : [ExceptionMapperRegistryBuilder#getGenericType](https://github.com/katharsis-project/katharsis-framework/blob/master/katharsis-core/src/main/java/io/katharsis/errorhandling/mapper/ExceptionMapperRegistryBuilder.java#L32): 
```
private Class<? extends Throwable> getGenericType(Class<? extends JsonApiExceptionMapper> mapper) {
        Type[] types = mapper.getGenericInterfaces();
        for (Type type : types) {
        	if (type instanceof ParameterizedType && (((ParameterizedType)type).getRawType() == JsonApiExceptionMapper.class || ((ParameterizedType)type).getRawType() == ExceptionMapper.class)) {
                //noinspection unchecked
                return (Class<? extends Throwable>)((ParameterizedType)type).getActualTypeArguments()[0];
            }
        }
        //Won't get in here
        return null;
}
```
`mapper` class is resolved correclty, the issue is that `mapper.getGenericInterfaces()` resolves only direct implementations (from javaDoc):
```
    * Returns the {@code Type}s representing the interfaces
    * directly implemented by the class or interface represented by
    * this object.
```

**Comment by k-sever** [comment]
Ok, seems like this one is a duplicate of #155. Should've look over open issues first. Closing this one
