### ISSUE TITLE
"-" is not allowed in resource filter when Katharsis upgarde to QuerySpec

### ISSUE THREAD

**Issue by zlhades3** [katharsis-project/katharsis-framework#318]
e.g.: "filter[Main-Task]","filter[Sub-Task]" will be reject.

**Comment by remmeier** [comment]
you may losen the regex expression in DefaultQuerySpecDeserializer a bit to support that. Currently I think only "/" is supported.

**Comment by zlhades3** [comment]
@remmeier , Yes, we rewrite DefaultQuerySpecDeserializer currently and hope this issue can be fix in future. Thanks you very much.

**Comment by remmeier** [comment]
PRs are welcomed :-)

**Comment by zlhades3** [comment]
@remmeier  I just get the last code and found that hyphen in resource name was fixed when you check Metamodule (#289). I just add one UT for my case and it was passed in currently develop branch.

**Comment by zlhades3** [comment]
BTW: Issue still there in attribut level, but try to  avaiable "-" in attribute level.
