### ISSUE TITLE
Cannot create an abstract base implementation for io.katharsis.errorhandling.mapper.ExceptionMapper

### ISSUE THREAD

**Issue by yuvalbo** [katharsis-project/katharsis-framework#332]
The code in https://github.com/katharsis-project/katharsis-framework/blob/bc4a06f637d2d7173e736220157c1eaa4e7fafe7/katharsis-core/src/main/java/io/katharsis/core/internal/exception/ExceptionMapperRegistryBuilder.java#L36

should be using something like Apache Commons Lang's `ClassUtils.getAllInterfaces(...)`  see [here](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/ClassUtils.html#getAllInterfaces-java.lang.Class-)

Otherwise there is no option to create an `abstract class` implementation for `ExceptionMapper` e.g to have a common handling/logging of error messages and codes in a single place and only extracting the specific exception details on the concrete classes implementing the base.

My current workaround is to declare the concrete classes as implementing the `io.katharsis.errorhandling.mapper.ExceptionMapper` interface in addition to my abstract class to pass the `ExceptionMapperRegistryBuilder` test

**Comment by chb0github** [comment]
Can you create a simple branch from master ? or at least supply some sample code? I more-or-less get what you're saying but need an example to run with

**Comment by yuvalbo** [comment]
Tried, cannot see to push
I am getting - 
Pushing to https://github.com/katharsis-project/katharsis-framework.git
remote: Permission to katharsis-project/katharsis-framework.git denied to yuvalbo.
fatal: unable to access 'https://github.com/katharsis-project/katharsis-framework.git/': The requested URL returned error: 403

**Comment by yuvalbo** [comment]
Since I could not push my branch see below snippet of the solution.

First one is from class: `ExceptionMapperRegistryBuilder`

``` java
    private Class<? extends Throwable> getGenericType(Class<? extends JsonApiExceptionMapper> mapper) {
        List<Class<?>> types = ClassUtils.getAllInterfaces(mapper);

        for (Type type : types) {
        	if (type instanceof ParameterizedType && (((ParameterizedType)type).getRawType() == JsonApiExceptionMapper.class || ((ParameterizedType)type).getRawType() == ExceptionMapper.class)) {
                //noinspection unchecked
                return (Class<? extends Throwable>)((ParameterizedType)type).getActualTypeArguments()[0];
            }
        }
        //Won't get in here
        return null;
    }
```


The second is addition to `io.katharsis.core.internal.utils.ClassUtils`

``` java

/**
	 * Taken from org.apache.commons.lang3.ClassUtils
	 */
	public static List<Class<?>> getAllInterfaces(final Class<?> cls) {
		if (cls == null) {
			return null;
		}

		final LinkedHashSet<Class<?>> interfacesFound = new LinkedHashSet<>();
		getAllInterfaces(cls, interfacesFound);

		return new ArrayList<>(interfacesFound);
	}

	/**
	 * Taken from org.apache.commons.lang3.ClassUtils
	 */
	private static void getAllInterfaces(Class<?> cls, final HashSet<Class<?>> interfacesFound) {
		while (cls != null) {
			final Class<?>[] interfaces = cls.getInterfaces();

			for (final Class<?> i : interfaces) {
				if (interfacesFound.add(i)) {
					getAllInterfaces(i, interfacesFound);
				}
			}

			cls = cls.getSuperclass();
		}
	}

```

**Comment by chb0github** [comment]
You have to fork the repo. I am surprised GH didn't offer to do it for you

**Comment by yuvalbo** [comment]
Cool, managed. You should be able to see it

**Comment by yuvalbo** [comment]
@chb0github well... seems its a bit more complex than I thought. Will try to devote more time to it

**Comment by yuvalbo** [comment]
@chb0github DONE now all tests pass, I did use Apache commons-lang3 `TypeUtils` class so see if it is ok with you

**Comment by chb0github** [comment]
Cool. I will have a look at it and seen if we can get it merged in

**Comment by chb0github** [comment]
Merged!
