### ISSUE TITLE
NPE in ResourcePatch.updateValues

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#351]
an additional check for null in the source is needed here:

```
  if (!source.containsKey(fieldName)) {
                    source.put(fieldName, new HashMap<>());
   }
```

otherwise a PATCH may fail to properly update resources with nested data structures.

**Comment by chb0github** [comment]
Did you make a fix?

**Comment by remmeier** [comment]
yes, tomorrow, but not a blocker if you want to release.
