### ISSUE TITLE
Add (integration independent) support to read request parameters and read/write request/response header

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#354]
- new interface RequestContext (or CallContext or...) with methods getRequestHeader, getRequestParameter, setResponseHeader, getResponseHeader (typically backed by thread-local or request-local to get access to the request and response of the current thread)
- method ModuleContext.setRequestContext(...) to be used by the various integrations to hook in their implementation.
- new method RequestContextAware with method setRequestContext that can be implemented by Repositories, DocumentFilter and RepositoryFilter to have access to parameters and headers.

Jaxrs already has a Thread-local to return information about the request uri, that mechanism can be extended support the use cases here as well. Other integrations can follow a similar pattern.

general nodes:
- various integrations (JAXRS, Servlet) provide native means to do that. here a integration-independent implementation is provided. That is vital for Katharsis modules to provide portability across different integrations
- RequestContext might be made available trough DI in some integrations (among other Katharsis objects)
- applications using Katharsis are free to use the native means to access those information since there is usually not need for portablity
- **request/response headers are typically used for security tokens, monitoring, corrs, etc. this kind of thins are typically best added to the underlying JAXRS, Servlet implementation, not to Katharsis**.

**Comment by remmeier** [comment]
Jaxrs already has a Thread-local to return information about the request uri, that mechanism can be extended support the use cases here as well.

**Comment by hibaymj** [comment]
To add to your second point in Spring MVC you can simply Autowire in the HttpServletRequest and HttpServletResponse objects into an implementation class.

To your last two bullet points, I don't see why this would need to be segregated in it's own interface hierarchy.  Every repository, should be request context aware, regardless of its deployment environment.

Adding these interfaces would unnecessarily complicate the implementation and use of the context.

Create a static method RequestContext.requestContext(); which can proxy the methods with a single interface.  We only support two servers at the moment JAX-RS and Spring MVC, there is no need over complicate the development or use of any additional functionality, now or in the foreseeable future.

**Comment by remmeier** [comment]
1. sure some/most integrations will provide some means to access those request/response objects, but that is not the point here. The point is to have a mechanism that is independent of the integration. That is of particular importance for modules that are supposed to work in different envirionments.

2. RequestContext.requestContext(); => no singletons and static methods, sorry

3. there is also the servlet integration in the offical repo. And at least personally I do have a forth one.

**Comment by hibaymj** [comment]
2. you have offered no reason why this extremely common and useful practice in every DI framework (and so far beyond) is not to be used.
1. You do have the mechanism which is independent of the mechanism, its the singleton access method.
3. Those additional integrations can provide a single class to support each additional module, which matches the design decisions of many other portions of the framework.

The solution to every problem is not adding more interfaces, this is a solution which is easily bounded and does not require the same user intervention.  Every server implementation you use will provide access to the request and response contexts in a similar enough fashion where complexity is not necessary.

**Comment by remmeier** [comment]
singleton access method are bad design, you may checkout common anti patterns.

**Comment by hibaymj** [comment]
While it may be a common anti-pattern for most scenarios, the concept of dependency injection relies entirely upon it to function.  Spraying the framework with subtle failure points, which you intend to be user managed is far worse than using a common anti-pattern.  Dogmatically following design principles without understanding the reason for their existence does not improve the code base.  I invite you to look at some Spring framework code, because their tools highly leverage singleton functionality for bean injection, so does Guice, and CDI.

Katharsis is a framework, not a product.  It's job is to make the lives easier for the developer's who consume it, not more difficult.

**Comment by remmeier** [comment]
> common anti-pattern for most scenarios

not for most, for all of them. 

exposing various objects in a DI environment like that RequestContext and various other objects is not the scope of this ticket.

**Comment by chb0github** [comment]
@remmeier - the user can easily wire in, using either JAX-RS with `@Context` or using spring (and I think spring MVC will also honor that annotation). I did this very thing with my last project. 

I mean, if you look at JAX-RS you have a variety of annotations for interrogating the inbound data: `@HeaderParam`, `@Context`, and if you want the body, straight up, you can either declare the method to take `@InputStream` or `byte[]` which will get you the raw 1's and 0's

In any event, Katharsis has no need as a framework to make this any easier than it already is.

Frankly, the design of Katharsis has serious limitations. To truly allow full control of response headers you would have to return an `Entity` which would require a total overhaul of our APIs.

**Comment by remmeier** [comment]
reset ticket with more detailed description to focus on the purpose of the ticket

**Comment by remmeier** [comment]
no longer needed
