### ISSUE TITLE
Must ResourceList be a List?

### ISSUE THREAD

**Issue by Ramblurr** [katharsis-project/katharsis-framework#357]
`ResourceList` implements List, which restricts usage. I believe it should be an `Iterable` or at least  a `Collection`.

Sets can also be pageable collections. 

Spring data's [`Page`](http://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Page.html), which serves basically the same purpose as ResourceList, [is an iterable](http://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Page.html)

Can we refactor it into a `ResourceCollection implements Collection` or `ResourcePage implements Iterable`?

**Comment by chb0github** [comment]
Can you explain how it restricts usage? The answer is it's probably fine to move the type up the call stack but we want to make sure we understand what problem we are trying to address.

**Comment by remmeier** [comment]
paging, sorting, the array of resources in the "data" section of a json api document all assume an ordered list of elements.

one could live with a Iterable (in a Katharsis 4.0), but for 99.9% of the use cases the list shouldbe fine and easier to use.

**Comment by chb0github** [comment]
Well, actually, what's assumed with the jsonapi spec is index ordering. There are no `List`, `Collection` or `Set` - there is only and array - it's closest object analog in java (expect the primitive) is a List - it's iteration order is it's insertion order. 

Honestly, I have had this discussion with many colleagues: Json doesn't order anything. Not keys in an object and not entries in a array. Java, on-the-other-hand allows total manipulation. This isn't so much of a problem with keys in an object but it's a deal breaker when trying to do a patch on an array; As a `Collection` with no declared ordering, you could GET elements: `[1,3,5]` and then submit a PATCH that says "set index 1 to 10" - but, if the marshalling of your patch request is interpretted as a `Set` then they is no such thing as an index; an index is faked by treating iteration order as index. 

Honestly, I think that _only_ list is appropriate - an `Iterable` gives no assurances.

**Comment by remmeier** [comment]
maybe it is also important to point out that those interfaces are used on the client side as well. I think we would make life a bit miserable for devleopers on the client when giving them just a list.

**Comment by weaselmetal** [comment]
`Iterable`s suck to program against, but `List`s are not compatible with `Set`s. I believe that most of the time, json api responses will in fact be sets, not containing duplicates. If your service layer returns sets for that reason (because the service layer intends to not deliver duplicates), then you will need to convert from sets to lists for every such service method. On the other hand, Hibernate, QueryDSL, JPA all default to `List`. So maybe `List` is fine, but `Collection` would be compatible with more return types.

**Comment by hibaymj** [comment]
I think @chb0github has it absolutely spot on.

It might be initially a bit counter intuitive, but it is important you don't introduce inconsistencies while attempting to make the framework easier to user on the consumer.  A list is the contract JSON provides, no more and no less.  Any other assumption is willfully inviting errors into the process.

**Comment by chb0github** [comment]
Unique elements are not the issue. Index order is

**Comment by Ramblurr** [comment]
I've been convinced by the arguments that a List is semantically correct, so I am fine with closing this issue.
