### ISSUE TITLE
Is there a way to add pre-post callbacks?

### ISSUE THREAD

**Issue by exports** [katharsis-project/katharsis-framework#360]
I'm using katharsis 3.0.0 with springboot now, and I want to set callbacks for specific katharsis resource action. For example, I want to set the creator of a created resource by accessing current security context, or perform further logging and auditing. thx!

**Comment by remmeier** [comment]
see dos (module section) => repository and document filters

there is https://github.com/katharsis-project/katharsis-framework/issues/354, but you should not need that if you are working with spring.
