### ISSUE TITLE
Nested filter parameter is not working

### ISSUE THREAD

**Issue by exports** [katharsis-project/katharsis-framework#361]
I'm using katharsis-jpa 3.0.0 with springboot. I have following entities `Appointment` and `User`.

When I use dot-style filter `/api/appointment?filter[user.id]=1`, it returns records correctly.

When I use nested filter `/api/appointment?filter[user][id]=<any existing user id>`, it returns all records regardless of the filter value.

```
@Entity
public class Appointment {
    @Id
    @GeneratedValue
    private Long id;

    @ManyToOne
    private User user;

   // getters and setters
}
```
```
@Entity
public class User {
    @Id
    @GeneratedValue
    private Long id;

    @OneToMany(mappedBy = "user")
    private List<Appointment> appointments = new ArrayList<>();

   // getters and setters
}

```

**Comment by remmeier** [comment]
there are two different ways of assembling urls:

1. filter[type][attributePath]
2. filter[attributePath]
3. filter[attr1][attr2] 

maybe the precendence of the two should change and there should be a way to disable one or the other url flavor  in DefaultQuerySpecDeserializer as an application usually sticks to one. In your case with attributes and types having the same name it gets ambiguous. A PR for that would be welcomed.

I guess there should be a way to disable at least 3.
