### ISSUE TITLE
Relationship Repo return wrong representation for 'self' relationship link...

### ISSUE THREAD

**Issue by arempala** [katharsis-project/katharsis-framework#427]
I'm using katharsis 3.0.1 with Spring, and the relationship self link (GET /articles/1/relationships/author) returns the whole author object. Should't that be just the type and id of the related resource?
```
{ "data": {
    "type": "people",
    "id": "12"
  }
}
```

GET /articles/1/author returns the whole author resource which to my knowledge is fine.

My relationship repo implements RelationshipRepositoryV2 interface and it's findOneTarget method.

**Comment by chb0github** [comment]
Can you link to the spec on this?

**Comment by arempala** [comment]
OK, the specs say that's what the response MAY look like. It's different from what Katharsis 2.x did, but it's still jsonapi compliant.
