### ISSUE TITLE
Getting Started 

### ISSUE THREAD

**Issue by bliet** [katharsis-project/katharsis-framework#428]
Maybe i forgot anything. But i tried to walk through the Getting started.

But at the step "Application" in the line
```
KatharsisFeature katharsisFeature = new KatharsisFeature(environment.getObjectMapper(), new
                SampleJsonServiceLocator());
```
a parameter is missing.

> constructor KatharsisFeature in class KatharsisFeature cannot be applied to given types;
  required: ObjectMapper,QueryParamsBuilder,JsonServiceLocator
  found: ObjectMapper,SampleJsonServiceLocator
  reason: actual and formal argument lists differ in length

**Comment by mohlek** [comment]
My KatharsisFeature looks like this. I hope this will help :)

```Java
@Provider
public class KatharsisFeature extends io.katharsis.rs.KatharsisFeature {

    @Override
    public boolean configure(FeatureContext context) {
        io.katharsis.rs.KatharsisFeature feature = new io.katharsis.rs.KatharsisFeature();
        DefaultQuerySpecDeserializer querySpecDeserializer = (DefaultQuerySpecDeserializer) feature
                .getQuerySpecDeserializer();
        querySpecDeserializer.setAllowUnknownAttributes(true);
        querySpecDeserializer.addSupportedOperator(new GroupFilterParameter());

        context.property(KatharsisProperties.RESOURCE_SEARCH_PACKAGE, "org.xxx")
                .property(KatharsisProperties.RESOURCE_DEFAULT_DOMAIN, "")
                .property(KatharsisProperties.WEB_PATH_PREFIX, "")
                .register(feature);

        return true;
    }
}
```

**Comment by bliet** [comment]
I just say it, so anyone can update the Getting Started. 

But thanks :-)

**Comment by mohlek** [comment]
Yeah I know. The documentations is not 100%. Currently we are changing some internals. There will be a few changes in the next weeks.

Thanks for the information.

**Comment by bliet** [comment]
Is there a example for JPA Module + Servlets integration?

**Comment by mohlek** [comment]
You could take a look at the tests from katharsis-jpa / katharsis-servlet sub module.
There are many examples.
