### ISSUE TITLE
How to use ValidationModule?

### ISSUE THREAD

**Issue by DavidDuwaer** [katharsis-project/katharsis-framework#429]
Hi,

I am not sure if this is the right place for this kind of question, please point me to the right please if so :).

I've tried to look for examples or documentation, but I cannot find anything except for the `katharsis-validation` tests and the [paragraph in the doc](http://katharsis-jsonapi.readthedocs.io/en/latest/user-docs.html#jsr-303-validation-module). From there I understand I must throw a `javax.validation.ValidationException` or a `javax.validation.ConstraintViolationException` when the input is wrong, and somehow attach the `Errors` object (to which my `org.springframework.validation.Validator` implementation attached the validation errors) to this exception, and Katharsis should translate the validation errors into a HTTP response containing a JSON object with the relevant errors.

I've included `io.katharsis:katharsis-validation` on the class path and I am throwing ValidationException errors, but they simply appear in the response as a normal 500 error response. Explain to me what to do to make it work (how to "activate" the ValidationModule in the first place and how to attach the `Errors` to the `Exception`) and I'll gladly write the doc for it :).

**Comment by chb0github** [comment]
Can you give a sample of code? Ideally using our basic example code? You
are right, it should

**Comment by chb0github** [comment]
Honestly, the `katharsis-validation` module is up for removal. The guy who wrote it left.

Try modifying the code below. I am 100% certain it works and if you change types you should get predictable results. Literally, just make sure this class is in the katharsis scan path and it should work

```
import io.katharsis.errorhandling.ErrorData;
import io.katharsis.errorhandling.ErrorResponse;
import io.katharsis.errorhandling.mapper.ExceptionMapperProvider;
import io.katharsis.errorhandling.mapper.JsonApiExceptionMapper;

import java.util.ArrayList;
import java.util.List;

import static org.springframework.http.HttpStatus.NOT_IMPLEMENTED;

@ExceptionMapperProvider
public class UnsupportedOperationExceptionMapper implements JsonApiExceptionMapper<UnsupportedOperationException> {

    @Override
    public ErrorResponse toErrorResponse(UnsupportedOperationException cve) {
        List<ErrorData> errors = new ArrayList<>();
        ErrorData error = ErrorData.builder()
                .setStatus(String.valueOf(NOT_IMPLEMENTED))
                .setTitle(cve.getMessage())
                .setCode(NOT_IMPLEMENTED +"")
                .build();

        errors.add(error);

        return ErrorResponse.builder().setStatus(NOT_IMPLEMENTED.value()).setErrorData(errors).build();
    }


}
```

**Comment by remmeier** [comment]
fyi the module is gone here, but development continues at www.crnk.io
