### ISSUE TITLE
How to update "errors" section without an exception

### ISSUE THREAD

**Issue by jvanantwerp** [katharsis-project/katharsis-framework#43]
We have several use cases where validation errors are occurred when a resource is updated via POST or PATCH.  According to the 1.0 spec I should be able to add these to the "errors" section of the document.

The way I am reading the documentation, `ErrorResponse` objects only get processed via an `Exception`.  Validation errors are not an exceptional condition so they shouldn't require an exception.  How can I have Katharsis serialize a JSON API Error Object into the "errors" section without an exception?

**Comment by meshuga** [comment]
Hi, now it can be possible by returning `io.katharsis.response.JsonApiResponse` with `errors` field filled in. I wish to fix some more bugs soon and name 2.5.0 release with this functionality.
