### ISSUE TITLE
ConstraintViolation.getMessage() always returns null when using ValidationModule

### ISSUE THREAD

**Issue by erdi** [katharsis-project/katharsis-framework#435]
I'm installing `ValidationModule` from 3.0.2 in the server and in `KatharsisClient` and the `ConstraintViolation`s  that are contained within `ConstraintViolationException`s thrown by the client always return `null` for their `message` property. 

I believe this is down to the `message` being set as the `title` of `ErrorData` in `ConstraintViolationExceptionMapper` but then read from `details` of `ErrorData` in `ConstraintViolationImpl`.

**Comment by chb0github** [comment]
Thanks for the info. What DI are you using?

**Comment by erdi** [comment]
Why would the DI I'm using and even if I'm using a DI matter for this?

**Comment by chb0github** [comment]
because spring already has several ready-to-go validators and you won't need to use the validation module. The original author of the validation module  is gone and the whole module has been removed. You're literally the first to use it.

**Comment by erdi** [comment]
I don't see what the fact that Spring has some ready-to-go validators has to do with this. The validation module was validator agnostic as it was about translating JSR-303's `ConstraintViolationException`s and `ValidationException`s to and from JSON API messages.

Thanks for letting me know that the module is gone. I reckon there is no point in this issue then so I'm closing it.

**Comment by chb0github** [comment]
It means you could use the one in spring and not worry about the behavior
in this module.
Since I knew the module was gone I was suggesting an alternative.

Good luck
