### ISSUE TITLE
Module API to allow to extend core katharsis functionality

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#45]
PR to follow soon. Module API was a prerequisite to implement https://github.com/katharsis-project/katharsis-framework/issues/15. Something similar to the Jackson module api would be beneficial I guess.

- new Module interface
- new SimpleModule class as basis for new modules
- ModuleRegistry holding the various modules and apply there changes to katharsis core
- registration of new ResourceInformationBuilder
- registration of new ResourceLookup
- registration of Jackson modules
- registration of repositories
- registration of filters to intercept requests

Created this ticket here to discuss the module part.

**Comment by ieugen** [comment]
I think this will be approached after version 3 and it is not clear (for me at least) from the description what are the benefits of introducing these modules or the problems it solves.

**Comment by remmeier** [comment]
the module api you mean? Are you familiar with the Jackson module api? It is quite popular because it allows third-party contributions to the core jackson implementation. And it also allowed to modularize jackson it self. In the context of katharsis my jpa module would be an example for that. It just makes use of the module api and does not need any further changes to katharsis core. People that would like to use it can register it to Katharsis. All other people do not need to bother with it (no depdencies, etc.). I imagine other candidates for modules could be:

- tracing
- metrics
- jsr 303 validation support (like ConstraintViolation exception mapping and validate incoming data) 
- dto mapping with something like mapstruct (would be nice to see together with the jpa module)
- caching
- ...

I could not imagine Jackson being there where it is without the module api :-) Hopefully that will hold for Katharsis as well some day.

Also agree with the refactored serialization part, that looks very good from what I have seen.

Regarding the serialization, etc. you can let me know where I can help/test. I will stay on the master until I can prepare the first pull request because the fork is already in use and has to be stable. Or if I was able to convience you already about the module api, that is something that would be quite independent to the serialization and could be applied next to it. That pr should also be reasonably small. I would not mind being able to contribute a first small part so that I have not to many forked changes.

**Comment by meshuga** [comment]
Thanks for the improvement @remmeier !
