### ISSUE TITLE
Make laziness of toOne relations configurable

### ISSUE THREAD

**Issue by weaselmetal** [katharsis-project/katharsis-framework#56]
Since commit 02f35e0d5b0dc3a8a29f17df1a1dd6bb77e78f3e all toOne related objects must be fetched lazily, with no other option. toMany relations could be fetched eagerly in contrast (or rather: the server may always include the relationship's reference data (type, id), no matter what).

This is neither very sensible nor consistent. `@JsonApiToOne` should have least also have the option to provide the relationship's data right away, by setting `@JsonApiToOne(lazy = false)`.

I'd advocate that the default for the `lazy` attribute should be `false`. I also think that such changes should be done with a little more caution. Which would mean that we should probably stick with a `lazy = true` default, even though I don't think it's very sensible.

@meshuga @masterspambot ?

**Comment by meshuga** [comment]
Yes, it was very unwise to introduce that change. I flagged it as a bug and make it `lazy = false` by default.

**Comment by weaselmetal** [comment]
Cool, thanks for the super fast fix @meshuga !
