### ISSUE TITLE
Exception mapping: not all http status codes may be returned correctly

### ISSUE THREAD

**Issue by weaselmetal** [katharsis-project/katharsis-framework#61]
Event though the jsonapi does not mention 405 http status, I think it would be appropriate status to let a client now that `DELETE` is not supported for a certain resource.
The 405 status  requires to include an `Allow` header (https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html), stating which methods are allowed for that resource. Also `javax.ws.rs.NotAllowedException` enforces that those methods are provided.
As far as I can tell, exceptions which are handled by a `@ExceptionMapperProvider` find no means to set header data on the returned `ErrorData` object. Meaning a valid 405 response cannot be produced.

**Comment by meshuga** [comment]
I think it should be possible to pass a framework specific object which would allow for custom modification e.g. for Spring framework it would be an instance of `HttpServletResponse`.

**Comment by meshuga** [comment]
I think the easiest thing would be to implement this method and using existing functionality pass the framework appropriate object to add `Allow` header. I don't think extending Katharsis to allow doing something sophisticated with the exception mappers will be something good.

**Comment by weaselmetal** [comment]
I think I don't fully agree. Could you extend on your idea how to add the headers? How would I pass this 'appropriate object'? Currently I can't think of a non-nasty way to do that.
Comparing katharsis to jersey: I can always return a `javax.ws.rs.core.Response` which allows me to create every response status correctly. E.g.

    return Response.status(Response.Status.METHOD_NOT_ALLOWED).allow(methods).build();

I don't see the katharsis way to do something similar.

**Comment by meshuga** [comment]
In Jersey you can call `ContainerRequestContext#abortWith(Response)`

**Comment by weaselmetal** [comment]
So you would inject the request context into the `ResourceRepository` and use the `abortWith(Response)` when an error occurred. Is that correct? That would make the exception mappers somewhat super fluent, don't you think?

**Comment by weaselmetal** [comment]
I request this issue to be re-opened. I think that it's not a viable solution to ignore the existence and need for response headers in katharsis. I'd be willing to create a fix for that.
`KatharsisInvokerContext` should take a `Map<String, String>` for setting response headers, as well as `BaseResponseContext`. Or only have a getter for this header data on the interfaces and a setter for implementations of those two interfaces.

@meshuga @masterspambot @keithdmoore @Ramblurr ?

**Comment by ieugen** [comment]
I tend to agree with you, with one objection: you can have multipleHttp headers with the same name. This might mean we should use a multi map.

http://stackoverflow.com/questions/3096888/standard-for-adding-multiple-values-of-a-single-http-header-to-a-request-or-resp

**Comment by meshuga** [comment]
OK, let's reopen this issue, you convinced me the Katharsis exception mappers should have a notion of resources, json paths etc.

**Comment by weaselmetal** [comment]
@ieugen from what I read at the given link, there may be multiple values for one header name, like:
`Allow: GET,POST,HEAD`. After all, the value side is a string, maybe containing colons.
Implementation would show if something like `Map<String, Set<String>>` would be needed / preferable.

**Comment by ieugen** [comment]
@weaselmetal : Yes, Map<String, Set<String>> is sometimes called a multi map. There are several implementations out there. 

I would not add the setXXX() method to the interface - to avoid spreading mutability in the API.

**Comment by mohlek** [comment]
I stuck on that too.

http://jsonapi.org/format/#fetching-resources-responses-404
katharsis doesn't respond as the specs define. I get a 200 response when my data is null.
As the specs define it should return a 404 with the current body.

Trying to return a 404 on my own didn't work neither.

```Java
	@JsonApiFindOne
	public final T findOne(TT id, ContainerRequestContext crc) throws GlobalError {
		try {
			user.setContainerRequestContext(crc);
			T t = findByID(id);
			if (t == null)
				crc.abortWith(Response.status(404).entity(new JsonApiResponse()).build());
			return t;
		} catch (Exception e) {
			if (e instanceof GlobalError)
				throw (GlobalError) e;
			throw new GlobalError("100", e.getMessage());
		}
	}
```

**Comment by buschtoens** [comment]
> ### [200 OK](http://jsonapi.org/format/#fetching-resources-responses-200)

> *[...]*

> `null` is only an appropriate response when the requested URL is one that might correspond to a single resource, but doesn’t currently.

> Note: Consider, for example, a request to fetch a to-one related resource link. This request would respond with `null` when the relationship is empty (such that the link is corresponding to no resources) but with the single related resource’s resource object otherwise.

> *[i.e. this only applies to requests to related records]*

> ```
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

>{
  "links": {
    "self": "http://example.com/articles/1/author"
  },
  "data": null
}
```

> *[...]*

> ### [404 Not Found](http://jsonapi.org/format/#fetching-resources-responses-404)

> A server MUST respond with 404 Not Found when processing a request to fetch a single resource that does not exist, except when the request warrants a 200 OK response with `null` as the primary data (as described above).

So, to reiterate: if a single record is requested by ID and doesn't exist, a `404 Not Found` status must be issued. The correct response body should not contain a `data` member, but an `error` member.

**Comment by chb0github** [comment]
This conversation had died in committee. Closing it until there is a PR
