### ISSUE TITLE
Support for source pointer computation in ExceptionMapper

### ISSUE THREAD

**Issue by remmeier** [katharsis-project/katharsis-framework#69]
the json api spec makes use of json pointers to give a source pointer for an error. This make the computation of a source pointer quite difficult:
- arrays needs to be accessed by index (e.g. for the inclusions)
- errors can occur both within the data and the inclusions section

Application-level validation frameworks like JSR-303 work on a different data structure than the original json api request. As a consequence, ExceptionMappers need to be able to map application errors like ConstraintViolation to sourcePointer. 

toErrorResponse should be enhanced by

`
toErrorResponse(Exception exception, ExceptionMapperRequestContext)
`

where as ExceptionMapperRequestContext provides a method

`
getSourcePointer(Serializable resourceId, String attributePath)
`

I do have an implementation of a JSR-303 ConstraintViolation exception mapper that can be used as a basis for a PR.

**Comment by weaselmetal** [comment]
Well, we rename a lot of things when exposing them on the API (e.g. also through `@JsonProperty("betterName")`), in hopes of giving things a clearer name. Meaning a ConstraintViolation would use different names than the json payload, breaking your idea, even though I like it. Would work fine though if all names were the same application wide.

**Comment by remmeier** [comment]
>  breaking your idea, even though I like it

that is kind of my point, developers work with simple java beans and then katharsis does a lot of stuff (convert to json api payload structure, rename attributes). As a consequence, katharsis should provide some support to help developers do the same with the sourcePointers.

**Comment by Ramblurr** [comment]
Yea this is a sticking point for us as well. I'd love to include the source pointer in errors dynamically, but we have no reliable way to backtrack and map the error to the original JSON attribute name.

**Comment by remmeier** [comment]
no longer needed
